[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".pyenv",
    ".pytest_cache",
    ".venv",
    ".vscode",
    "venv",
    "src/HUD",
    "src/custom_logging",
    "src/characterization",
    "src/debugging_scripts",
    "src/logs",
    "src/exo"
]

[tool.pylint]
disable = ["C0301"]